# Generated by Django 3.1.7 on 2021-03-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqid', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InquiryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('CountryCode', models.IntegerField(max_length=10)),
                ('mobileNo', models.IntegerField(max_length=10)),
                ('message', models.CharField(max_length=512)),
                ('ReqId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B2B_App.identifiertable')),
            ],
        ),
    ]
