# Generated by Django 3.1.7 on 2021-03-18 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirytable',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
